# I am a comment, and I want to say that the variable CC will be
# the compiler to use.
CC=g++
# Hey!, I am comment number 2. I want to say that CFLAGS will be the
# options I'll pass to the compiler.
CFLAGS=-Wall -std=c++11 -o

#default:make
#all:make

make:my_main.cpp
	$(CC) $(CFLAGS) my_main.cpp

launch:algo_fuzzy_advanced.exe
	./a.out test_result_breast_cancer_wisconsin_modified_normalized

clean:
	rm *.out
