CWfuzzy_before:fuzzyCW_before.cc updateDis.o
	g++ -o CWfuzzy_before fuzzyCW_before.cc updateDis.o

updateDis.o:updateDis.cc
	g++ -c updateDis.cc

clean:
	rm -f *.o#CWfuzzy_app:fuzzyCW_app.cc updateDis.o


#CWfuzzy_app:fuzzyCW_app.cc updateDis.o
#	g++ -o CWfuzzy_app fuzzyCW_app.cc updateDis.o